spring.application.name=product-service
server.port = 4000


#Postgres Config
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres123


#JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

#PRODUCTION
#springdoc.api-docs.enabled=false